// 1. Implement Autio-Retry Promises
// 2. Throttle Promises by batching
// 3. Async iterator
// 4. Promise Class
// 5. Full Debounce => Implement a JavaScript debounce function that accepts a function fn, a delay delay, and optional { leading, trailing } configuration. The returned function should delay execution until calls stop for the specified delay, ensuring only the latest call is executed, while preserving this and forwarding all arguments. Support leading execution on the first call, trailing execution after the final call, and correctly handle leading + trailing together without executing the trailing call when there was only a single invocation. The returned debounced function should also provide .cancel() to cancel any pending execution and .flush() to immediately execute a pending trailing invocation. Internal state such as timers, latest arguments, and this should remain private through closures.
// 6. Promise.race => Implement a function that accepts any iterable of values, Promises, or thenables and returns a new Promise that settles as soon as the first input settles. If the first input fulfills, the returned Promise should fulfill with that value; if the first input rejects, the returned Promise should reject with that reason. Non-Promise values should be treated as already-fulfilled values. The implementation must preserve native Promise behavior for an empty iterable and must not use Promise.race internally.
// 7. Promse.any => Implement a function that accepts any iterable of values, Promises, or thenables and returns a new Promise that fulfills as soon as the first input fulfills. Rejections from individual inputs should be ignored until every input has rejected. If all inputs reject, the returned Promise should reject with an AggregateError containing all rejection reasons in the same order as the original iterable. Non-Promise values should be treated as already-fulfilled values. For an empty iterable, the returned Promise should reject with an AggregateError containing an empty errors array. Do not use native Promise.any.
// 8. Promise.allSettled => Implement a JavaScript function Promise.myAllSettled(iterable) that accepts any iterable containing values, Promises, or thenables and returns a new Promise that fulfills only after every input has settled, regardless of whether each input fulfills or rejects. The returned Promise must always fulfill unless the iterable itself cannot be consumed, and its result must be an array preserving the original input order, where each fulfilled input produces { status: "fulfilled", value } and each rejected input produces { status: "rejected", reason }. Non-Promise values should be treated as immediately fulfilled, array holes should be treated as undefined, and an empty iterable should resolve with an empty array. Do not use native Promise.allSettled internally.
// 9.
